apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.mailerlite.task.com
spec:
  group: mailerlite.task.com
  names:
    kind: Email
    listKind: EmailList
    plural: emails
    singular: email
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              senderConfigRef:
                type: string
              recipientEmail:
                type: string
              subject:
                type: string
              body:
                type: string
          status:
            type: object
            properties:
              deliveryStatus:
                type: string
              messageId:
                type: string
              error:
                type: string
